### ISSUE TITLE
Ignore index in `scsplit`

### ISSUE THREAD

**Issue by roger-yu-ds** [DanilZherebtsov/verstack#6]
Is it possible to have a feature to ignore index in `scsplit`? Currently, if the index is not ordered, an error is thrown `IndexError: positional indexers are out-of-bounds`. Thanks.

**Comment by DanilZherebtsov** [comment]
Hi Roger! Not sure what you mean. scsplit works irregardless of the index: it will split the data frame if the index is ordered and if the index is unordered.

Could you please provide some data and code to reproduce the problem you are referring to?

**Comment by roger-yu-ds** [comment]
Hi Danil, sure!

I just tested this. So while what you said is true, that an out of order index is fine, the problem seems to be that the index has to contain the sequential numbers [0, len(arr)].

In my case I've filtered out some rows, but I want to keep the index values to be joined to another data set after modelling.

```
# index = [0, 1, 2] # works
# index = [1, 2, 0] # works
index = [1, 2, 3] # IndexError
# index = [0, 1, 3] # IndexError

X_dummy = pd.DataFrame({'a': [1, 2, 3], 'b': [1, 2, 3]}, index=index)
y_dummy = pd.Series([1, 2, 3])

scsplit(X_dummy, y_dummy, stratify=y_dummy)
```

The workaround I use so far is to 
1. save the index in another variable
2. `reset_index()`
3. `scsplit()`
4. reassign the original indexes

**Comment by DanilZherebtsov** [comment]
Ok, I see. 

Looks like if the actual object index max value is greater than the max value of ordered (starting from 0) index of an object - it throws this error.

Can't find a reason to justify this, so you are right - this needs to be fixed. Will do this some time soon.

And how did you manage to then reinstate original indexes after the split? I mean it is easy for dummy data, but for a large dataset this this could potentially mess up your indexes. 
I would suggest saving not just the original index, but original index next to ordered index in a dictionary format, so that you could map it after the split.

**Comment by DanilZherebtsov** [comment]
I have to say: the case is very unusual. I would prefer to keep indexes strictly in the range(0,N) as it may create confusion interpreting the splits due to the conventional practice.
Added an exception for such rare cases to inform users to reset index before applying scsplit.
